package net.osdn.gokigen.gr2control.camera.fuji_x.wrapper.values;

public interface IFujiXFilmSimulation
{
    int FILM_SIMULATION_MIN = 1;
    int FILM_SIMULATION_PROVIA  =1;
    int FILM_SIMULATION_VELVIA  =2;
    int FILM_SIMULATION_ASTIA  =3;
    int FILM_SIMULATION_MONOCHROME  =4;
    int FILM_SIMULATION_SEPIA  =5;
    int FILM_SIMULATION_PRO_NEG_HI  =6;
    int FILM_SIMULATION_PRO_NEG_STD  =7;
    int FILM_SIMULATION_MONOCHROME_Y_FILTER  =8;
    int FILM_SIMULATION_MONOCHROME_R_FILTER  =9;
    int FILM_SIMULATION_MONOCHROME_G_FILTER  =10;
    int FILM_SIMULATION_CLASSIC_CHROME  =11;
    int FILM_SIMULATION_ACROS  =12;
    int FILM_SIMULATION_ACROS_Y  =13;
    int FILM_SIMULATION_ACROS_R  =14;
    int FILM_SIMULATION_ACROS_G  =15;
    int FILM_SIMULATION_ETERNA  =16;
    int FILM_SIMULATION_CLASSIC_NEGATIVE = 17;
    int FILM_SIMULATION_MAX = 18;

    String FILM_SIMULATION_PROVIA_STR  = "PROVIA";
    String FILM_SIMULATION_VELVIA_STR  = "Velvia";
    String FILM_SIMULATION_ASTIA_STR  = "ASTIA";
    String FILM_SIMULATION_MONOCHROME_STR  = "MONOCHROME";
    String FILM_SIMULATION_SEPIA_STR  = "SEPIA";
    String FILM_SIMULATION_PRO_NEG_HI_STR  = "PRO Neg. Hi";
    String FILM_SIMULATION_PRO_NEG_STD_STR  = "PRO Neg. Std";
    String FILM_SIMULATION_MONOCHROME_Y_FILTER_STR  = "MONOCHROME+Ye";
    String FILM_SIMULATION_MONOCHROME_R_FILTER_STR  = "MONOCHROME+R";
    String FILM_SIMULATION_MONOCHROME_G_FILTER_STR  = "MONOCHROME+G";
    String FILM_SIMULATION_CLASSIC_CHROME_STR  = "CLASSIC CHROME";
    String FILM_SIMULATION_ACROS_STR  = "ACROS";
    String FILM_SIMULATION_ACROS_Y_STR  = "ACROS+Ye";
    String FILM_SIMULATION_ACROS_R_STR  = "ACROS+R";
    String FILM_SIMULATION_ACROS_G_STR  = "ACROS+G";
    String FILM_SIMULATION_ETERNA_STR  = "ETERNA";
    String FILM_SIMULATION_CLASSIC_NEGATIVE_STR = "CLASSIC Neg.";

}
